"""Generate Spectre's favicon (SVG) and app icons (PNG) from the mark geometry.

Run: `uv run python tools/make_icons.py`. No dependency: PNGs are rasterised with zlib only.
The icon is the simplified Spectre mark: five emission lines whose tops form a dome, two gaps
for eyes and an uneven hem — a ghost drawn from a spectrum.
"""

from __future__ import annotations

import struct
import zlib
from pathlib import Path

STATIC = Path(__file__).resolve().parents[1] / "src" / "spectre" / "web" / "static"
GROUND = (0x12, 0x13, 0x15)
# Seven emission lines (real wavelength colours) packed into one silhouette: the tops are cut by a
# circle (the head), two gaps are the eyes, alternating bottoms are the hem. 64-unit grid.
HEAD = (32.0, 29.0, 21.0)  # centre x, centre y, radius
WIDTH = 5.0
STEP = 6.3
COLOURS = [
    (0xA0, 0x84, 0xFF),  # 405 nm
    (0x7D, 0x86, 0xFF),  # 436 nm
    (0x4F, 0xC3, 0xF7),  # 486 nm  Scout
    (0x8B, 0xD4, 0x50),  # 546 nm  Scribe
    (0xFF, 0xD2, 0x3F),  # 589 nm  Warden
    (0xFF, 0x9F, 0x43),  # 615 nm
    (0xEF, 0x5F, 0x6F),  # 656 nm
]
BOTTOMS = [50, 46, 53, 47, 53, 46, 50]
EYES = {1: (23.0, 31.0), 2: (23.0, 31.0), 4: (23.0, 31.0), 5: (23.0, 31.0)}
LINES = [(32 + (i - 3) * STEP, BOTTOMS[i], COLOURS[i], EYES.get(i)) for i in range(7)]
RADIUS = 13.0


def head_top(x: float) -> float:
    cx, cy, r = HEAD
    dx = abs(x - cx)
    return cy - (r * r - dx * dx) ** 0.5 if dx < r else cy


def svg() -> str:
    cx, cy, r = HEAD
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">',
        f'<defs><clipPath id="h"><circle cx="{cx:g}" cy="{cy:g}" r="{r:g}"/>'
        f'<rect x="{cx - r:g}" y="{cy:g}" width="{2 * r:g}" height="{64 - cy:g}"/>'
        "</clipPath></defs>",
        f'<rect width="64" height="64" rx="{RADIUS:g}" fill="#121315"/>',
        '<g clip-path="url(#h)">',
    ]
    for x, bottom, rgb, gap in LINES:
        colour = "#{:02X}{:02X}{:02X}".format(*rgb)
        top = cy - r
        segments = [(top, bottom)] if gap is None else [(top, gap[0]), (gap[1], bottom)]
        for y0, y1 in segments:
            parts.append(
                f'<rect x="{x - WIDTH / 2:g}" y="{y0:g}" width="{WIDTH:g}" '
                f'height="{y1 - y0:g}" fill="{colour}"/>'
            )
    parts.append("</g></svg>")
    return "".join(parts) + "\n"


def coverage(px: float, py: float, scale: float) -> tuple[float, tuple[int, int, int]]:
    """Return (alpha of the rounded tile, colour) at the centre of pixel (px, py)."""
    x, y = (px + 0.5) / scale, (py + 0.5) / scale
    # rounded-square tile
    cx = min(max(x, RADIUS), 64 - RADIUS)
    cy = min(max(y, RADIUS), 64 - RADIUS)
    inside = (x - cx) ** 2 + (y - cy) ** 2 <= RADIUS**2
    if not inside:
        return 0.0, GROUND
    for lx, bottom, rgb, gap in LINES:
        if abs(x - lx) <= WIDTH / 2 and head_top(x) <= y <= bottom:
            if gap is not None and gap[0] < y < gap[1]:
                continue
            return 1.0, rgb
    return 1.0, GROUND


def png(size: int, *, maskable: bool = False) -> bytes:
    # 4x supersampling for smooth edges; maskable icons fill the square (no transparent corners).
    ss = 4
    scale = size * ss / 64
    rows = []
    for py in range(size):
        row = bytearray([0])
        for px in range(size):
            acc = [0.0, 0.0, 0.0, 0.0]
            for sy in range(ss):
                for sx in range(ss):
                    alpha, rgb = coverage(px * ss + sx, py * ss + sy, scale)
                    if maskable:
                        alpha = 1.0
                    acc[0] += rgb[0] * alpha
                    acc[1] += rgb[1] * alpha
                    acc[2] += rgb[2] * alpha
                    acc[3] += alpha
            n = ss * ss
            a = acc[3] / n
            if a:
                row += bytes(round(acc[i] / n / a) for i in range(3)) + bytes([round(a * 255)])
            else:
                row += bytes(4)
        rows.append(bytes(row))

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
        )

    header = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    text = b"Source\x00Generated by tools/make_icons.py from the Spectre mark geometry"
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"tEXt", text)
        + chunk(b"IDAT", zlib.compress(b"".join(rows), 9))
        + chunk(b"IEND", b"")
    )


def main() -> None:
    (STATIC / "favicon.svg").write_text(svg(), encoding="utf-8")
    icons = STATIC / "icons"
    icons.mkdir(exist_ok=True)
    for size in (32, 180, 192, 512):
        (icons / f"icon-{size}.png").write_bytes(png(size, maskable=size == 180))
    (icons / "icon-maskable-512.png").write_bytes(png(512, maskable=True))
    print("icons written to", icons)


if __name__ == "__main__":
    main()
